### ISSUE TITLE
Make the image self-contained with the techdocs-cli

### ISSUE THREAD

**Issue by mrmartan** [backstage/techdocs-container#28]
Is is currently hard to consume and invoke in CI/CD pipelines running jobs on Kubernetes clusters where arbitrary docker/docker-in-docker execution is disabled (for security reasons).

## Actual

Custom image:

```Dockerfile
FROM node:lts-buster
RUN apt-get update && apt-get install -y gcc musl-dev openjdk-11-jdk curl graphviz ttf-dejavu fontconfig python3 python3-pip
# Install techdocs
RUN npm install -g @techdocs/cli
RUN pip3 install mkdocs-techdocs-core==0.*
# Download plantuml file, Validate checksum & Move plantuml file
RUN curl -o plantuml.jar -L http://sourceforge.net/projects/plantuml/files/plantuml.1.2021.4.jar/download && echo "be498123d20eaea95a94b174d770ef94adfdca18  plantuml.jar" | sha1sum -c - && mv plantuml.jar /opt/plantuml.jar
# Create script to call plantuml.jar from a location in path
RUN echo '#!/bin/sh\n\njava -jar /opt/plantuml.jar ${@}' >> "/usr/local/bin/plantuml"
RUN chmod +x "/usr/local/bin/plantuml"
# Install yq
RUN wget https://github.com/mikefarah/yq/releases/download/v4.9.5/yq_linux_amd64 -O /usr/bin/yq &&\
    chmod +x /usr/bin/yq
CMD bash
````

CI job:

```yaml
.techdocs:
  image: private.container.registry/custom/techdocs
  script:
    - techdocs-cli generate --no-docker
    - techdocs-cli publish ...
```

## Expected/wanted

This is to illustrate the general idea.

CI job:

```yaml
.techdocs:
  image: docker.io/backstage/techdocs:version
  script:
    - techdocs-cli generate --ci
    - techdocs-cli publish ...
```
