### ISSUE TITLE
Support minify plugin

### ISSUE THREAD

**Issue by ctoestreich** [backstage/techdocs-container#38]
We are using the following plugins and would like to support minify by default

```
plugins:
  - search # necessary for search to work
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: iso_datetime
  - awesome-pages
```
